### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leshacat** [netdata/netdata-cloud#234]
**Describe the bug**	
Login to dashboard shows blank page. If create a brand new account and login, the dashboard shows. Tried deleting cache/cookies logging in after again, and it still shows blank page.

**To Reproduce**	
- Log in

**Expected behavior**	
Dashboard should be visible

**Screenshots**	
_[https://imgur.com/a/APQ4N8K](https://imgur.com/a/APQ4N8K)_	

```
**Error logs**	
analytics.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
recorder.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
aptrinsic.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
4567453.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
collectedforms.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
fb.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
leadflows.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
4567453.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
conversations-embed.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
spaces:1 Failed to load resource: the server responded with a status of 500 ()
app.2ad6a66b4432350be740.chunk.js:341 GET https://app.netdata.cloud/api/v1/spaces 500
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:341
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:341
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:2
e.exports @ app.2ad6a66b4432350be740.chunk.js:2
e.exports @ app.2ad6a66b4432350be740.chunk.js:2
u.request @ app.2ad6a66b4432350be740.chunk.js:2
r.forEach.u.<computed> @ app.2ad6a66b4432350be740.chunk.js:2
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:2
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:341
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:341
U3.o @ app.2ad6a66b4432350be740.chunk.js:341
G5 @ app.2ad6a66b4432350be740.chunk.js:533
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:533
y @ app.2ad6a66b4432350be740.chunk.js:533
(anonymous) @ app.2ad6a66b4432350be740.chunk.js:533
app.2ad6a66b4432350be740.chunk.js:341 Error: Request failed with status code 500
    at e.exports (app.2ad6a66b4432350be740.chunk.js:2:2047456)
    at e.exports (app.2ad6a66b4432350be740.chunk.js:2:3701748)
    at XMLHttpRequest.x (app.2ad6a66b4432350be740.chunk.js:2:2045832)
```

**Desktop (please complete the following information):**	
 - OS: Windows 10 Pro x64
 - Browser Brave with shields disabled for NetData website
 - Version unknown

It used to work then all of the sudden the page went blank and I could not use it. I tried logging in with a new user and it shows the dashboard but when I log out and back in to the account that has my nodes it still shows a blank page. I've disabled shields and adblockers and also cleared cache/cookies and it still shows blank page.

**Comment by leshacat** [comment]
All of the sudden it started showing again today... Closing ticket. Will re-open if problem persists.
