### ISSUE TITLE
[BUG] charts are not rendering anything, even with data.

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#326]
**Describe the bug**	
This issue came from a bug reported on our [discord server](https://discord.com/channels/847502280503590932/950255983261794324), charts on Single Node view are rendering but not displaying any data.

We have different a cases:
1. Y-axis is properly set, from 0 to X GiB, tooltip shows values but nothing is rendered on the chart
![image](https://user-images.githubusercontent.com/82235632/157067405-cd77cae7-0ca9-45a9-b8a1-548edb4ed992.png)

2. Y-axis shows some values, not from 0, which don't seem to cover Y-value displayed on the tooltip
![image](https://user-images.githubusercontent.com/82235632/157067629-626a5f8e-f25d-4eb8-af67-6c4b66bb8b7d.png)

Request: `https://app.netdata.cloud/api/v1/nodes/<REDACTED>/data?v2=&chart=mem.available&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&_=1646667141350&points=274&group=average&gtime=0&after=-599`

<details>
<summary> sample of /data response for above request</summary>

```json
{
   "api": 1,
   "id": "mem.available",
   "name": "mem.available",
   "view_update_every": 5,
   "update_every": 5,
   "first_entry": 1646501085,
   "last_entry": 1646666310,
   "before": 1646666310,
   "after": 1646665715,
   "dimension_names": ["avail"],
   "dimension_ids": ["MemAvailable"],
   "latest_values": [4770.5117188],
   "view_latest_values": [4770.512],
   "dimensions": 1,
   "points": 120,
   "format": "json",
   "result": {
 "labels": ["time", "avail"],
    "data":
 [
      [ 1646665715000, 4799.77],
      [ 1646665720000, 4799.68],
      [ 1646665725000, 4799.441],
      [ 1646665730000, 4799.684],
      [ 1646665735000, 4799.531],
      [ 1646665740000, 4798.57],
      [ 1646665745000, 4794.672],
      [ 1646665750000, 4794.664],
      [ 1646665755000, 4791.281],
      [ 1646665760000, 4791.586],
      [ 1646665765000, 4801.207],
      [ 1646665770000, 4801.207],
      [ 1646665775000, 4800.965],
      [ 1646665780000, 4800.086],
      [ 1646665785000, 4799.934],
      [ 1646665790000, 4799.812],
      [ 1646665795000, 4799.691],
      [ 1646665800000, 4798.781],
      [ 1646665805000, 4800.363],
      [ 1646665810000, 4791.035],
      [ 1646665815000, 4787.25],
      [ 1646665820000, 4789.914],
      [ 1646665825000, 4800.34],
      [ 1646665830000, 4800.941],
      [ 1646665835000, 4800.266],
      [ 1646665840000, 4794.77],
      [ 1646665845000, 4792.066],
      [ 1646665850000, 4790.348],
      [ 1646665855000, 4791.047],
      [ 1646665860000, 4774.875],
      [ 1646665865000, 4774.207],
      [ 1646665870000, 4772],
      [ 1646665875000, 4771.637],
      [ 1646665880000, 4781.902],
      [ 1646665885000, 4772.328],
      [ 1646665890000, 4772.148],
      [ 1646665895000, 4772],
      [ 1646665900000, 4782.906],
      [ 1646665905000, 4782.902],
      [ 1646665910000, 4780.836],
      [ 1646665915000, 4780.074],
      [ 1646665920000, 4779.074],
      [ 1646665925000, 4776.297],
      [ 1646665930000, 4779.875],
      [ 1646665935000, 4779.512],
      [ 1646665940000, 4779.27],
      [ 1646665945000, 4779.391],
      [ 1646665950000, 4790.926],
      [ 1646665955000, 4790.895],
      [ 1646665960000, 4791.141],
      [ 1646665965000, 4789.566],
      [ 1646665970000, 4789.262],
      [ 1646665975000, 4789.422],
      [ 1646665980000, 4788.211],
      [ 1646665985000, 4788.992],
      [ 1646665990000, 4789.242],
      [ 1646665995000, 4789.242],
      [ 1646666000000, 4789.242],
      [ 1646666005000, 4789.09],
      [ 1646666010000, 4788.727],
      [ 1646666015000, 4787.305],
      [ 1646666020000, 4787.188],
      [ 1646666025000, 4786.945],
      [ 1646666030000, 4786.945],
      [ 1646666035000, 4786.711],
      [ 1646666040000, 4787.285],
      [ 1646666045000, 4787.508],
      [ 1646666050000, 4787.508],
      [ 1646666055000, 4778.418],
      [ 1646666060000, 4790.512],
      [ 1646666065000, 4800.117],
      [ 1646666070000, 4799.996],
      [ 1646666075000, 4799.918],
      [ 1646666080000, 4799.797],
      [ 1646666085000, 4799.676],
      [ 1646666090000, 4799.773],
      [ 1646666095000, 4799.383],
      [ 1646666100000, 4799.148],
      [ 1646666105000, 4799.309],
      [ 1646666110000, 4796.434],
      [ 1646666115000, 4794.496],
      [ 1646666120000, 4794.125],
      [ 1646666125000, 4792.035],
      [ 1646666130000, 4785.809],
      [ 1646666135000, 4786.051],
      [ 1646666140000, 4786.023],
      [ 1646666145000, 4786.547],
      [ 1646666150000, 4786.426],
      [ 1646666155000, 4786.547],
      [ 1646666160000, 4785.699],
      [ 1646666165000, 4785.945],
      [ 1646666170000, 4783.613],
      [ 1646666175000, 4783.188],
      [ 1646666180000, 4783.309],
      [ 1646666185000, 4783.312],
      [ 1646666190000, 4783.395],
      [ 1646666195000, 4783.512],
      [ 1646666200000, 4783.391],
      [ 1646666205000, 4783.141],
      [ 1646666210000, 4783.07],
      [ 1646666215000, 4781.594],
      [ 1646666220000, 4780.625],
      [ 1646666225000, 4780.746],
      [ 1646666230000, 4780.988],
      [ 1646666235000, 4781.734],
      [ 1646666240000, 4781.883],
      [ 1646666245000, 4781.52],
      [ 1646666250000, 4781.754],
      [ 1646666255000, 4780.625],
      [ 1646666260000, 4781.383],
      [ 1646666265000, 4781.297],
      [ 1646666270000, 4781.176],
      [ 1646666275000, 4782.875],
      [ 1646666280000, 4782.27],
      [ 1646666285000, 4782.602],
      [ 1646666290000, 4781.992],
      [ 1646666295000, 4774.75],
      [ 1646666300000, 4770.328],
      [ 1646666305000, 4769.602],
      [ 1646666310000, 4770.512]
  ]
},
 "min": 4769.602,
 "max": 4801.207
}
```

</details>

**To Reproduce**	
- Unknown

**Expected behavior**	
Data should be rendered on the charts

**Screenshots**	
(see above)

**Error logs**	
N/A

**Desktop (please complete the following information):**	

**Additional context**
User reported that this only happens on a specific server and on that particular server, netdata was installed to `/opt/netdata`, although on the other servers it was installed to `/etc/netdata`; the same os, ubuntu bionic

doing: `./edit-config go.d/web_log.conf` on `/opt/netdata` opens this file: `/opt/netdata/etc/netdata/go.d/web_log.conf` on `$EDITOR`
but executing: `/opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin -d -m web_log`
gives me: `[ INFO  ] main[main] setup.go:123 found '/usr/lib/netdata/conf.d/go.d/web_log.conf`

Seems like netdata put multiple occurrences of: `2022-03-07 22:17:29: netdata INFO  : PLUGINSD[python.d] : RRDSET: chart name 'web_log_nginx.http_method' on host '<REDACTED>' already exists.` into it's error.log with various chart names

**Comment by hugovalente-pm** [comment]
@novykh @kaskavel this came from a user report on discord, I think I saw a similar error like this in the past but can't recall what was the issue.

**Comment by hugovalente-pm** [comment]
user as come back saying that error still occurs and he sees an error on the console

![image](https://user-images.githubusercontent.com/82235632/157253537-aaba4668-667a-4e07-ba82-150ccc32183b.png)

<details> 
<summary> error </summary>

```
pp.3ad57563b31e3156fdab.chunk.js:2 Uncaught (in promise) Error: Tried to set the value of Recoil selector visitedNodes__"1bd84e66-feb6-4c4e-b3d6-524040134721"__withFallback using an updater function, but it is an async selector in a pending or error state; this is not supported.
    at app.3ad57563b31e3156fdab.chunk.js:2:4097758
    at oe (app.3ad57563b31e3156fdab.chunk.js:2:4097839)
    at app.3ad57563b31e3156fdab.chunk.js:2:4098725
    at Object.replaceState (app.3ad57563b31e3156fdab.chunk.js:2:4108401)
    at se (app.3ad57563b31e3156fdab.chunk.js:2:4098541)
    at app.3ad57563b31e3156fdab.chunk.js:2:4098876
    at Object.trace (app.3ad57563b31e3156fdab.chunk.js:2:4092918)
    at ce (app.3ad57563b31e3156fdab.chunk.js:2:4098862)
    at de (app.3ad57563b31e3156fdab.chunk.js:2:4099068)
    at o (app.3ad57563b31e3156fdab.chunk.js:2:4113208)
    at app.3ad57563b31e3156fdab.chunk.js:529:18510
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
oe @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
replaceState @ app.3ad57563b31e3156fdab.chunk.js:2
se @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
trace @ app.3ad57563b31e3156fdab.chunk.js:2
ce @ app.3ad57563b31e3156fdab.chunk.js:2
de @ app.3ad57563b31e3156fdab.chunk.js:2
o @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:529
await in (anonymous) (async)
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
pu @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
batchUpdates @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:2
(anonymous) @ app.3ad57563b31e3156fdab.chunk.js:1636
Lu @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
t.unstable_runWithPriority @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
Wl @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
Pu @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
(anonymous) @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
F @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
k.port1.onmessage @ npm.react.dom.03191f8b732f98d6c4a7.chunk.js:2
```
</details>

**Comment by hugovalente-pm** [comment]
@novykh @dimko we got another user with a similar scenario like this, discussion on this [discord thread](https://discord.com/channels/847502280503590932/966963779617300511)

**Comment by hugovalente-pm** [comment]
this last user mentioned that he got it to work, not sure if related, by:
* removing the agent and then re-installed again
* thinking it could have been something to do with the Fedora kernel update.
See this  ... https://discordapp.com/channels/847502280503590932/921399690728206366/964061066483085342

**Comment by novykh** [comment]
1st unfortunately the response provided is not from the affected charts displayed on the screenshots.
2nd if removing the agent and re-install fixes it, then it looks like a backend/agent issue.

If we cannot get our hands on the actual data responses of the affected charts we cannot be sure though.

**Comment by dimko** [comment]
Ok I think I managed to reproduce this one, but can't be sure if it's the exact case. The thing is that there is no /data request issued by the FE for this chart. For some reason the chart was missing from the /charts request, If I refresh the page though it's returned normally.

**Comment by hugovalente-pm** [comment]
@dimko, as spoken since this exact case isn't reproducible, and the user is not interested/supporting the troubleshooting, lets close this

**Comment by dimko** [comment]
Managed to reproduce it and collect the data required. Unless we do some manipulation of responses in the Backend, there seems to be an issue with agent's response. So...

for the following POST request 

`https://testing.netdata.cloud/api/v2/nodes/06415279-2790-4b38-b1c4-4bb2d9758bc0/data?v2=&chart=net.veth035bba2&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&_=1653555020232&points=197&group=average&gtime=0&after=-900`

with **Payload**

` v2: 
chart: net.veth035bba2
format: json
options: jsonwrap|nonzero|flip|ms
_: 1653555020232
points: 197
group: average
gtime: 0
after: -900`

The response coming from the BE is:

`{
  "after": 1653486756,
  "api": 1,
  "before": 1653486759,
  "dimension_ids": [
    "received",
    "sent"
  ],
  "dimension_names": [
    "received",
    "sent"
  ],
  "dimensions": 2,
  "first_entry": 1653486755,
  "format": "json",
  "id": "net.veth035bba2",
  "last_entry": 1653486759,
  "latest_values": [
    43.7177618,
    -37.4512228
  ],
  "max": 43.71776,
  "meta": {
    "coverage": 0,
    "hops": 0
  },
  "min": -37.45122,
  "name": "net.veth035bba2",
  "points": 4,
  "result": {
    "data": [
      [
        1653486756000,
        0,
        -1.19138
      ],
      [
        1653486757000,
        0.5644719,
        -2.123957
      ],
      [
        1653486758000,
        26.19381,
        -21.97212
      ],
      [
        1653486759000,
        43.71776,
        -37.45122
      ]
    ],
    "labels": [
      "time",
      "received",
      "sent"
    ]
  },
  "update_every": 1,
  "view_latest_values": [
    43.71776,
    -37.45122
  ],
  "view_update_every": 1
}`

@papazach @juacker @TonyPath / @stelfrag @odynik

**Comment by hugovalente-pm** [comment]
to add some additional info, the request was being done for the last 15min from today (26th of May) and the information we get on the response is coming with data from the 25th of May

**Comment by cakrit** [comment]
This really doesn't look like a cloud issue to me, but an edge case on the agent. If @dimko manages to reproduce again, he will issue the exact same request directly on the agent too, to verify. If that's the case, then @stelfrag will need to be invited to look at it at that moment.

**Comment by cakrit** [comment]
Moved it back to needs triage as we still don't know why it happens.

**Comment by hugovalente-pm** [comment]
I think @dimko has identified how this is reproducible, so we really need @MrZammler and/or @stelfrag to help here

**Comment by stelfrag** [comment]
> I think @dimko has identified how this is reproducible, so we really need @MrZammler and/or @stelfrag to help here

@dimko please share info to investigate

**Comment by dimko** [comment]
@stelfrag @hugovalente-pm Unfortunately, I don't have specific steps to reproduce. I was just playing around trying to reproduce another issue when I saw this. I'll try to do it again later today and will ping you.

**Comment by dimko** [comment]
Issue related to https://github.com/netdata/netdata/issues/12314

**Comment by MrZammler** [comment]
I believe I'm seeing it now on an agent connected to staging.

![image](https://user-images.githubusercontent.com/1905463/173786148-556d7aaf-e1df-43ff-92b6-dbe686dc0e9f.png)

The response from the agent to queries has a (weird) timestamp 15 days ago:

`http://192.168.0.50:19999/api/v1/data?v2=&chart=mem.committed&format=json&options=jsonwrap|nonzero|flip|ms&_=1655282445673&points=608&group=average&gtime=0&after=-900&with_metadata=true`
```

{
   "api": 1,
   "id": "mem.committed",
   "name": "mem.committed",
   "view_update_every": 1,
   "update_every": 1,
   "first_entry": 1653924643,
   "last_entry": 1653987214,
   "before": 1653987214,
   "after": 1653986315,
   "group": "average",
   "options": "nonzero,flip,jsonwrap,ms",
   "dimension_names": ["Committed_AS"],
   "dimension_ids": ["Committed_AS"],
   "latest_values": [144.8125],
   "view_latest_values": [144.8125],
   "dimensions": 1,
   "points": 900,
   "format": "json",
   "result": {
 "labels": ["time","Committed_AS"],
    "data":
 [
 [ 1653986315000,131.24219],
 [ 1653986316000,131.24219],
 [ 1653986317000,131.24219],
 [ 1653986318000,131.24219],
 [ 1653986319000,131.24219],
 [ 1653986320000,131.24219],
 [ 1653986321000,131.24219],
 [ 1653986322000,131.24219],
 [ 1653986323000,131.25781],
 [ 1653986324000,131.27344],
```

**Comment by MrZammler** [comment]
Could be a shot in the dark, but if/when this happens again, can we check that the clock on the host machine where the agent runs is ok ? Just to rule that out as a cause ? I tried to see from the screenshots here if there is such an indication but can't see any. If the user shares something from their logs, we could check from there.

Went through the discord threads as well, did the user pilus sent you a video as well @hugovalente-pm  ?

**Comment by hugovalente-pm** [comment]
@MrZammler unfortunately I don't have a video, the user had provided access to a local dashboard with that agent but it is no longer available :(

**Comment by stelfrag** [comment]
@dimko  A fix has been merged https://github.com/netdata/netdata/pull/13159 

If you can verify and are happy with this fix, we can close this

**Comment by dimko** [comment]
Thanks @stelfrag I checked regression and don't see any breaks. 
I reproduced the scenario that was initially breaking doing the following steps:

1. Spin up a netdata and claim it to cloud using docker
2. Navigate to one of the **veth** charts
3. Wait for a bit to collect data
4. Restart container
5. The previously present **veth** chart is no longer present on the agent so it has stopped collecting

What we see in the cloud when filtering for the last 15 mins for example where we had data for that chart.
![image](https://user-images.githubusercontent.com/19268853/174295045-5f1d70fa-e556-4c7d-b766-40d1780cbdbf.png)

When filtering for the last 2 mins for example where data collection has stopped, we now display an error that chart doesn't have data, while previously we were just showing an empty chart.
![image](https://user-images.githubusercontent.com/19268853/174295156-a685f241-77cb-4416-8a78-0a7e060ee5ce.png)


I believe the fix is sufficient and the UX is acceptable. @hugovalente-pm what do you think? I say we close it.
