### ISSUE TITLE
[Bug]: 500 page and Console error when adding back to room a previously removed node 

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#412]
### Bug description

The 500 error page is displayed in nodes table view and a console error is thrown in FE when a user adds back a node previously removed and room has no other nodes.

Refreshing the page fixes the issue.

### Expected behavior

The connect nodes blank slate is displayed instead of the 500 page

### Steps to reproduce

1. Claim a Node to a room
2. Room has a single node
3. Remove Node from room
4. Add Node back to the room

### Error Logs

> app.750f9fe062dce132368b.chunk.js:440 TypeError: Cannot read properties of undefined (reading 'mlCapable')
    at InnerRow (app.750f9fe062dce132368b.chunk.js:1796:4588)
    at ti (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:59492)
    at Wo (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:112134)
    at xu (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:99114)
    at ku (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:99042)
    at wu (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:98905)
    at du (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:95871)
    at npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:45260
    at t.unstable_runWithPriority (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:122869)
    at Wl (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:45037)
    at Hl (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:45205)
    at Bl (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:45140)
    at ou (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:93240)
    at Ti (npm.react.dom.acb8c798a6c7db4d2089.chunk.js:2:64817)
    at app.750f9fe062dce132368b.chunk.js:2:4238753
    at Qn (app.750f9fe062dce132368b.chunk.js:2:4231605)
    at Object.c [as replaceState] (app.750f9fe062dce132368b.chunk.js:2:4233499)
    at pt (app.750f9fe062dce132368b.chunk.js:2:4218367)
    at mt (app.750f9fe062dce132368b.chunk.js:2:4218551)
    at bt (app.750f9fe062dce132368b.chunk.js:2:4218883)
    at set (app.750f9fe062dce132368b.chunk.js:2:4247151)
    at app.750f9fe062dce132368b.chunk.js:1192:2579

### Desktop

OS: MacOS
Browser: chrome
Browser Version: 100.0.4896.60

**Comment by ivangergo3** [comment]
It is not happening for me, I have just tested on the staging environment
@burbuli8ra can you reproduce it?

**Comment by burbuli8ra** [comment]
@ivangergo3 I have been able to see the error, although I am not quite sure when it is caused, so @dimko the PR is merged in `develop`, can you please verify that the fix is working?

**Comment by burbuli8ra** [comment]
Released on [v2.29.0](https://github.com/netdata/cloud-frontend/releases/tag/2.29.0)
