### ISSUE TITLE
[Bug]: Single node view crashes when clicking Add to Dasboard

### ISSUE THREAD

**Issue by dimko** [netdata/netdata-cloud#652]
### Bug description

When user is in single node view and tries to create a dashboard for a chart, single node view crashes and a console error is thrown.

### Expected behavior

Option to create Custom Dashboard should be displayed, for the specific node

### Steps to reproduce

1. Navigate to Single Node view tab for a specific agent
2. Click Add to dashboard button on the top right corner of a chart

### Screenshots

![image](https://user-images.githubusercontent.com/19268853/201335416-453eb18b-5d4e-47ce-91f6-80f87eb4d2d7.png)

leads to 

![image](https://user-images.githubusercontent.com/19268853/201336138-9f7e2303-25b2-4e25-ab63-2a8e2e76b973.png)

### Error Logs

Error thrown in chrome dev console
```
app.5a07427caf0e2f168c85.js:2 TypeError: Cannot read properties of undefined (reading 'context')
    at p5 (app.5a07427caf0e2f168c85.js:2:2753234)
    at xi (npm.react.dom.942a022820e46f93c5e8.js:2:180397)
    at xu (npm.react.dom.942a022820e46f93c5e8.js:2:237637)
    at bc (npm.react.dom.942a022820e46f93c5e8.js:2:226573)
    at vc (npm.react.dom.942a022820e46f93c5e8.js:2:226501)
    at gc (npm.react.dom.942a022820e46f93c5e8.js:2:226364)
    at ac (npm.react.dom.942a022820e46f93c5e8.js:2:223144)
    at lc (npm.react.dom.942a022820e46f93c5e8.js:2:221695)
    at x (app.5a07427caf0e2f168c85.js:2:3703809)
    at MessagePort.T (app.5a07427caf0e2f168c85.js:2:3704343)
```

### Desktop

OS: MacOs
Browser Chrome
Browser Version 106

**Comment by dimko** [comment]
This is fixed, closing.
