### ISSUE TITLE
[Bug]: When searching for instances an entry on composite chart bar the page crashes with a console error

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/netdata-cloud#671]
### Bug description

When searching for an instance using the composite chart bar the page crashes with error TypeError: r.toLowerCase is not a function.
Not sure this is related to the high number of instances or something specific with the name of some/one of them.

### Expected behavior

Page should not crash and filtering should be applied.

### Steps to reproduce

1. Go to Kubernetes container > mem section [here](https://staging.netdata.cloud/spaces/netdata-cloud-stg/rooms/k8s-prd/overview#after=-900&before=0&utc=Europe%2FLisbon&offset=%2B0&timezoneName=Dublin%2C%20Lisbon&modal=&modalTab=&a558234b-0e42-425f-91b5-343f8ffdcf09-overview-chartName=menu_Kubernetes_Containers_submenu_mem&a558234b-0e42-425f-91b5-343f8ffdcf09-k8s-chartName=menu_Kubernetes_State&metrics_correlation=false&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=)
2. On instances component try to search for something
3. Page crashes and console error is visible

### Screenshots

https://user-images.githubusercontent.com/82235632/203370895-095a326b-509b-4fdc-acea-b044a54c4025.mp4

### Error Logs

```
app.5632a5d52dc22768c162.js:2 TypeError: r.toLowerCase is not a function
    at app.5632a5d52dc22768c162.js:2:449742
    at Array.filter (<anonymous>)
    at app.5632a5d52dc22768c162.js:2:449598
    at Object.Xi [as useMemo] (npm.react.dom.942a022820e46f93c5e8.js:2:184808)
    at t.useMemo (app.5632a5d52dc22768c162.js:2:3736029)
    at f (app.5632a5d52dc22768c162.js:2:449539)
    at xi (npm.react.dom.942a022820e46f93c5e8.js:2:180397)
    at Po (npm.react.dom.942a022820e46f93c5e8.js:2:192085)
    at xu (npm.react.dom.942a022820e46f93c5e8.js:2:238520)
    at bc (npm.react.dom.942a022820e46f93c5e8.js:2:226573)
    at vc (npm.react.dom.942a022820e46f93c5e8.js:2:226501)
    at gc (npm.react.dom.942a022820e46f93c5e8.js:2:226364)
    at ac (npm.react.dom.942a022820e46f93c5e8.js:2:223144)
    at uc (npm.react.dom.942a022820e46f93c5e8.js:2:223535)
    at Wl (npm.react.dom.942a022820e46f93c5e8.js:2:164118)
    at sc (npm.react.dom.942a022820e46f93c5e8.js:2:223986)
    at Le (npm.react.dom.942a022820e46f93c5e8.js:2:133260)
    at Br (npm.react.dom.942a022820e46f93c5e8.js:2:155936)
    at qn (npm.react.dom.942a022820e46f93c5e8.js:2:140332)
    at $n (npm.react.dom.942a022820e46f93c5e8.js:2:140116)
    at HTMLDivElement.o (app.5632a5d52dc22768c162.js:2:2335925)
(anonymous) @ app.5632a5d52dc22768c162.js:2
fo @ npm.react.dom.942a022820e46f93c5e8.js:2
a.componentDidCatch.t.callback @ npm.react.dom.942a022820e46f93c5e8.js:2
Ua @ npm.react.dom.942a022820e46f93c5e8.js:2
ku @ npm.react.dom.942a022820e46f93c5e8.js:2
bu @ npm.react.dom.942a022820e46f93c5e8.js:2
bu @ npm.react.dom.942a022820e46f93c5e8.js:2
bu @ npm.react.dom.942a022820e46f93c5e8.js:2
yu @ npm.react.dom.942a022820e46f93c5e8.js:2
(anonymous) @ npm.react.dom.942a022820e46f93c5e8.js:2
wc @ npm.react.dom.942a022820e46f93c5e8.js:2
uc @ npm.react.dom.942a022820e46f93c5e8.js:2
Wl @ npm.react.dom.942a022820e46f93c5e8.js:2
sc @ npm.react.dom.942a022820e46f93c5e8.js:2
Le @ npm.react.dom.942a022820e46f93c5e8.js:2
Br @ npm.react.dom.942a022820e46f93c5e8.js:2
qn @ npm.react.dom.942a022820e46f93c5e8.js:2
$n @ npm.react.dom.942a022820e46f93c5e8.js:2
o @ app.5632a5d52dc22768c162.js:2
```

### Desktop

Browser Version [e.g. 22]

**Comment by hugovalente-pm** [comment]
@dimko @novykh placing this as medium since 20/30 people using this for day and not sure how many face this issue but we this is serious since app crashes

**Comment by dimko** [comment]
On top of what you wrote @hugovalente-pm, when page crashes this way it's really hard for user to recover and bring it back in a working state. User has to like refresh page and change space or room in order for this error to get away. Feels like an important one preventing users using the app as expected.

**Comment by hugovalente-pm** [comment]
fixed
